### ISSUE TITLE
how to use with mmdetection?

### ISSUE THREAD

**Issue by imerse** [TylerYep/torchinfo#166]
when I use this tool with mmdetection, 
```
model = init_detector(config_file, checkpoint_file, device='cuda:0')
summary(model, (1, 3, 1333, 800))
```
There is such an error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torchinfo/torchinfo.py", line 261, in forward_pass
    _ = model.to(device)(*x, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/host/dev/code/SOLO/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'img_meta'

The above exception was the direct cause of the following exception:
```

**Comment by TylerYep** [comment]
The error message is saying to call your model, you pass in an input tensor and an img_meta param. you should pass that to summary() as a kwarg.

I would also advise you to pass in the input tensor directly via input_data instead of using input_size.

**Comment by TylerYep** [comment]
Closing due to inactivity. Feel free to reopen if you have followup questions.
