### ISSUE TITLE
Support of Unpooling-Layers

### ISSUE THREAD

**Issue by Delo971** [TylerYep/torchinfo#25]
Hello, first of all great project!  :)

For a univerity-project I am implementing all lot of autoencoders. For a lot of them your projects works fine. The problem is autoencoders that use Unpooling-Layers, there always comes an Exception

For example lets take this really simple Architecture, with one unpooling Layer

```
class Autoencoder(nn.Module):
    def __init__(self):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Sequential( 
            nn.Conv2d(3, 16, 3, padding=1),
            nn.ReLU(),
        )
        self.pool=nn.MaxPool2d(2, 2,return_indices=True)
        self.unpool =nn.MaxUnpool2d(2,2)
        self.decode =nn.Sequential(nn.Conv2d(16,3,3,padding=1),nn.ReLU())

    def forward(self, input):
        input= self.encoder(input)
        unpooled_shape = input.size()
        input,indices =self.pool(input)
        input =self.unpool(input=input, indices=indices, output_size=unpooled_shape)
        input = self.decode(input)
        return input
```
if you run `summary(model,input_size=(1,3,64,64))` you will get this Traceback

```
Traceback (most recent call last):
  File "/home/delo/anaconda3/envs/autoencoder/lib/python3.8/site-packages/torchinfo/torchinfo.py", line 153, in summary
    _ = model.to(device)(*x, **kwargs)
  File "/home/delo/anaconda3/envs/autoencoder/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/delo/Schreibtisch/autoencoder-procgen/src/model_stubs/experimental/autoencoder_unpool.py", line 29, in forward
    input =self.unpool(input=input, indices=indices, output_size=unpooled_shape)
  File "/home/delo/anaconda3/envs/autoencoder/lib/python3.8/site-packages/torch/nn/modules/module.py", line 731, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/delo/anaconda3/envs/autoencoder/lib/python3.8/site-packages/torchinfo/torchinfo.py", line 325, in hook
    info.input_size = info.calculate_size(inputs, batch_dim)
  File "/home/delo/anaconda3/envs/autoencoder/lib/python3.8/site-packages/torchinfo/layer_info.py", line 82, in calculate_size
    size = nested_list_size(inputs)
  File "/home/delo/anaconda3/envs/autoencoder/lib/python3.8/site-packages/torchinfo/layer_info.py", line 56, in nested_list_size
    if hasattr(inputs[0], "size") and callable(inputs[0].size):
IndexError: tuple index out of range
```

I tried to debug it, but this was out of my range. My gut is telling my, that is has something todo with the indices the pooling layers get. :D

Thank you in advance!

**Comment by TylerYep** [comment]
Hi, it looks like you get the correct result if you replace your unpool in forward() with:

```
input =self.unpool(input, indices=indices, output_size=unpooled_shape)
```
