### ISSUE TITLE
get_total_memory_used fails to handle list of str

### ISSUE THREAD

**Issue by minostauros** [TylerYep/torchinfo#254]
https://github.com/TylerYep/torchinfo/blob/73ed5687acfd6199b77fa1dcb65aa54762c1b720/torchinfo/torchinfo.py#L501

```
>>> get_total_memory_used(["abc", "def"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/torchinfo/torchinfo.py", line 503, in get_total_memory_used
    result = traverse_input_data(
  File "/usr/local/lib/python3.9/dist-packages/torchinfo/torchinfo.py", line 447, in traverse_input_data
    result = aggregate(
TypeError: unsupported operand type(s) for +: 'int' and 'str'
>>> 
```

**Comment by minostauros** [comment]
This happens when an input of a model is a list of strings, e.g., language models.
