### ISSUE TITLE
Either deal with or skip `jit.ScriptModule`

### ISSUE THREAD

**Issue by JakobHavtorn** [TylerYep/torchinfo#55]
When running `torchinfo.summary` on a model that contains modules scripted with `torch.jit.script` or modules that are constructed as `torch.jit.ScriptModule`s, the following error is raised:

```
Traceback (most recent call last):
  File "/home/jdh/repos/vseq/miscellaneous/reproduce_torchinfo_bug.py", line 41, in <module>
  File "/home/jdh/.conda/envs/vseq/lib/python3.9/site-packages/torchinfo/torchinfo.py", line 153, in summary
    apply_hooks(named_module, model, batch_dim, summary_list, idx, hooks)
  File "/home/jdh/.conda/envs/vseq/lib/python3.9/site-packages/torchinfo/torchinfo.py", line 382, in apply_hooks
    apply_hooks(
  File "/home/jdh/.conda/envs/vseq/lib/python3.9/site-packages/torchinfo/torchinfo.py", line 378, in apply_hooks
    hooks.append(module.register_forward_pre_hook(pre_hook))
  File "/home/jdh/.conda/envs/vseq/lib/python3.9/site-packages/torch/jit/_script.py", line 723, in fail
    raise RuntimeError(name + " is not supported on ScriptModules")
RuntimeError: register_forward_pre_hook is not supported on ScriptModules
```

To reproduce

```
import torch
import torch.nn as nn
import torchinfo


class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.layers = nn.Sequential(
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, 1),
        )

    def forward(self, x):
        return self.layers(x)


model = Model()
model_jit = torch.jit.script(model)

print(model)
print(model_jit)

x = torch.randn(64, 128)

# this succeeds
y = model(x)

# this succeeds
y = model_jit(x)

# this succeds
torchinfo.summary(model, input_data=x)

# this fails
torchinfo.summary(model_jit, input_data=x)
```

Ideally, `torchinfo` deals correctly with scripted modules. Alternatively, it doesn't attempt to summarize them and instead prints a warning that a scripted module was skipped.

**Comment by TylerYep** [comment]
This has been fixed in https://github.com/TylerYep/torchinfo/commit/737436099552d2f0ef3ef91e57a11531ab88904f

Thanks for raising the issue. This is a preliminary solution, so if you see additional ways to improve the (limited) output with JIT scripted modules, please let me know.

I'll cut the new release sometime this weekend.
