### ISSUE TITLE
Support ModuleDict

### ISSUE THREAD

**Issue by sevagh** [TylerYep/torchinfo#59]
Hello. I have a nn.Module which uses an nn.ModuleDict to store individual nn.Modules within it.

I suspect this should be a similar code addition to the ModuleList support: https://github.com/TylerYep/torchinfo/pull/11

Currently when I run torchinfo.summary on a module with a ModuleDict inside it, I get this error:
```
Traceback (most recent call last):
  File "/home/sevagh/.conda/envs/umx-gpu/lib/python3.9/site-packages/torchinfo/torchinfo.py", line 183, in summary
    _ = model.to(device)(**x, **kwargs)
TypeError: keywords must be strings

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sevagh/repos/umx-sliCQ/scripts/train.py", line 476, in <module>
    main()
  File "/home/sevagh/repos/umx-sliCQ/scripts/train.py", line 345, in main
    torchinfo.summary(unmix, input_data=jagged_slicq)
  File "/home/sevagh/.conda/envs/umx-gpu/lib/python3.9/site-packages/torchinfo/torchinfo.py", line 190, in summary
    raise RuntimeError(
RuntimeError: Failed to run torchinfo. See above stack traces for more details. Executed layers up to: []
```

**Comment by TylerYep** [comment]
Can you add code for a model (as short as possible) that uses a module dict? Thanks!

**Comment by TylerYep** [comment]
As far as I know, ModuleDicts should already work in torchinfo. Make sure you are passing additional arguments as kwargs in your forward() function.
```
        class ModuleDictModel(nn.Module):
            def __init__(self):
                super().__init__()
                self.choices = nn.ModuleDict(
                    {"conv": nn.Conv2d(10, 10, 3), "pool": nn.MaxPool2d(3)}
                )
                self.activations = nn.ModuleDict(
                    [["lrelu", nn.LeakyReLU()], ["prelu", nn.PReLU()]]
                )

            def forward(self, x, layer_type, activation_type):
                x = self.choices[layer_type](x)
                x = self.activations[activation_type](x)
                return x

        summary(
            ModuleDictModel(),
            input_data=torch.randn(1, 10, 3, 3),
            layer_type="conv",
            activation_type="lrelu",
        )
```
```
==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
ModuleDictModel                          --                        --
├─ModuleDict: 1                          --                        --
│    └─Conv2d: 2-1                       [1, 10, 1, 1]             910
├─ModuleDict: 1                          --                        --
│    └─LeakyReLU: 2-2                    [1, 10, 1, 1]             --
==========================================================================================
Total params: 910
Trainable params: 910
Non-trainable params: 0
Total mult-adds (M): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================
```

**Comment by sevagh** [comment]
Yeah, I agree with you. This is related to the way this library passes arguments to the forward function (from `input_data` or `input_shape`), and that I use non-standard arguments.
