### ISSUE TITLE
Summary doesn't work for huggingface models

### ISSUE THREAD

**Issue by kgarg8** [TylerYep/torchinfo#68]
**Describe the bug**
`torchinfo` can't produce summary of huggingface models.

**Stacktrace:**
```
Traceback (most recent call last):
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torchinfo/torchinfo.py", line 258, in forward_pass
    _ = model.to(device)(*x, **kwargs)
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/transformers/modeling_bert.py", line 1326, in forward
    return_dict=return_dict,
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/transformers/modeling_bert.py", line 825, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/transformers/modeling_bert.py", line 207, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torch/nn/functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "stack.py", line 5, in <module>
    summary(model, input_size=(16, 512))
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torchinfo/torchinfo.py", line 192, in summary
    model, x, batch_dim, cache_forward_pass, device, **kwargs
  File "/Users/krishna/opt/anaconda3/envs/T5_KPGen/lib/python3.7/site-packages/torchinfo/torchinfo.py", line 270, in forward_pass
    ) from e
RuntimeError: Failed to run torchinfo. See above stack traces for more details. Executed layers up to: []
```

**To Reproduce**
```
from torchinfo import summary
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)
summary(model, input_size=(16, 512))
```

**Expected behavior**
Summary should be printed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: N/A
 - Version: 10.14.6

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
```
transformers v4.9.0
torchinfo v4.5.2
```

**Proposed solution**
https://stackoverflow.com/questions/68577198/pytorch-summary-fails-with-huggingface-model/68577755#68577755

**Comment by TylerYep** [comment]
I expect this will break all models that expect a floattensor as the default dtype. Can you just use the `dtype` parameter in `summary()` instead?

**Comment by kgarg8** [comment]
yeah, this works although it might be slightly unintuitive for a new user:

`summary(model, input_size=(2, 512), dtypes=['torch.IntTensor'])`

**Comment by TylerYep** [comment]
We can try floattensor first and if that falls, try inttensor in our code. 

But all changes need to be backwards compatible, so I will unfortunately need to close the PR. Thank you for investigating this issue! Ill try to make the docs more clear for what to do here

**Comment by TylerYep** [comment]
Updated the documentation in https://github.com/TylerYep/torchinfo/commit/d228d353c700df11b59c1d71ec70bc8af9823421
